//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppForWritingTables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.Guid EventId { get; set; }
        public string Time { get; set; }
        public string Duration { get; set; }
        public string billerGroupId { get; set; }
        public string billerId { get; set; }
        public string bankRoutingNumber { get; set; }
        public string bankAccountNumber { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string streetAddress1 { get; set; }
        public string streetAddress2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string nameOnAccount { get; set; }
        public string phone { get; set; }
        public string companyName { get; set; }
        public Nullable<System.Guid> paymentReferenceId { get; set; }
        public string paymentChannel { get; set; }
        public Nullable<decimal> paymentAmount { get; set; }
    }
}
